# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
