# Generated by Django 5.0.6 on 2024-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
