# Generated by Django 5.0.6 on 2024-06-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_alter_discountcode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
