# Generated by Django 5.0.6 on 2024-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_order_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
