# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_remove_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
