# Generated by Django 5.0.6 on 2024-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_alter_otp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50, null=True, verbose_name='نام کامل'),
        ),
    ]
