# Generated by Django 5.0.6 on 2024-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_alter_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
